# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue! Please make sure you've followed our issue template. A team member will get back to you soon.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines and make sure you've followed our pull request template.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉

# Add 'triage' label to any new issues
labelToAddToNewIssues: triage
