name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd server && npm ci
          
      - name: Build frontend
        run: npm run build
        
      - name: Create deployment artifact
        run: |
          tar -czf release.tar.gz build/ server/ package.json package-lock.json README.md
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release.tar.gz
          
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
